### ISSUE TITLE
无法启动的问题解决办法（已解决）

### ISSUE THREAD

**Issue by qinshenxue** [vimplus/Vue2-Demo#1]
由于用sass用的少，没发现此类问题，我启动后也报错了
![image](https://cloud.githubusercontent.com/assets/10354498/24444229/435b521a-1498-11e7-8cde-ebb456f13675.png)
这个是由于sass本身构建的机制（对sass不是很了解），图中也提示了解决办法就是
`npm rebuild node-sass`
执行后，发现是去图中的地址下载一个文件
![image](https://cloud.githubusercontent.com/assets/10354498/24444343/8f9020c0-1498-11e7-8f65-4fcec3398e4f.png)
但是发现下载慢（需要梯子下载才快），而且不容易成功，于是自己手动下载，下载地址：[https://github.com/sass/node-sass/releases/download/v4.5.1/win32-x64-48_binding.node](https://github.com/sass/node-sass/releases/download/v4.5.1/win32-x64-48_binding.node)
下载完成后，将win32-x64-48_binding.node放到
`Vue2-Demo\node_modules\node-sass\vendor\win32-x64-48\`
文件夹下，win32-x64-48_binding.node要改名为：binding.node
接着应该就可以了。

**Comment by Joyotang** [comment]
可以考虑使用淘宝的镜像：

```
$ npm set registry https://registry.npm.taobao.org # 注册模块镜像
$ npm set disturl https://npm.taobao.org/dist # node-gyp 编译依赖的 node 源码镜像
```

针对node-sass这个问题可以单独设置node-sass的镜像，执行：

```
$ npm set sass_binary_site http://cdn.npm.taobao.org/dist/node-sass # node-sass 二进制包镜像
```

后面就可以愉快的下载了，我们公司各种网络限制都能快速下载无压力~

更多相关国内npm安装的问题可以参考：
[在中国，安装 & 升级 npm 依赖的正确方法](https://sebastianblade.com/the-truly-way-to-install-upgrade-npm-dependency-in-china/?from=timeline)

**Comment by qinshenxue** [comment]
我会把这个解决办法放到我文章中。
